create database customer_behaviour;

use customer_behaviour;

-- drop database Sales_Analysis --
select * from customer;

-- Q1. What is the total revenue generated by male vs. female customers?
SELECT 
    Gender, SUM(`Purchase Amount (USD)`) as Revenue
FROM
    customer
GROUP BY Gender;

-- Q2. Which customers used a discount but still spent more than the average purchase amount?
SELECT 
    `Customer ID`, `Purchase Amount (USD)`
FROM
    customer
WHERE
    `Discount Applied` = 'Yes'
        AND `Purchase Amount (USD)` >= (SELECT 
            AVG(`Purchase Amount (USD)`)
        FROM
            customer);
            
-- Q3. Which are the top 5 products with the highest average review rating?
SELECT 
    `Item Purchased`,
    ROUND(AVG(`Review Rating`), 2) AS Avg_Rating
FROM
    customer
GROUP BY `Item Purchased`
ORDER BY AVG(`Review Rating`) DESC
LIMIT 5;

-- Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 
SELECT 
    `Shipping Type`, ROUND(AVG(`Purchase Amount (USD)`), 2)
FROM
    customer
WHERE
    `Shipping Type` IN ('Standard' , 'Express')
GROUP BY `Shipping Type`;

-- Q5. Do subscribed customers spend more? Compare average spend and total revenue
SELECT 
    `Subscription Status`,
    COUNT(`Customer ID`) AS total_customers,
    ROUND(AVG(`Purchase Amount (USD)`), 2) AS avg_spend,
    ROUND(SUM(`Purchase Amount (USD)`), 2) AS total_spend
FROM
    customer
GROUP BY `Subscription Status`
ORDER BY total_spend , avg_spend DESC;

-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT 
    `Item Purchased`,
    ROUND(100 * SUM(CASE
                WHEN `Discount Applied` = 'Yes' THEN 1
                ELSE 0
            END) / COUNT(*),
            2) AS discount_rate
FROM
    customer
GROUP BY `Item Purchased`
ORDER BY discount_rate
LIMIT 5;

-- Q7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment. 
with customer_type as (
select `Customer ID`, `Previous Purchases`,
case
when `Previous Purchases` = 1 then 'New'
when `Previous Purchases` between 2 and 10 then 'Returning'
else 'Loyal'
END as customer_segment from customer)

SELECT 
    customer_segment, COUNT(*) AS 'Number of Customers'
FROM
    customer_type
GROUP BY customer_segment;

-- Q8. What are the top 3 most purchased products within each category? 
with item_count as (
select Category, `Item Purchased`, 
count(`Customer ID`) as total_order,
row_number() over( partition by Category order by count(`Customer ID`) desc) as item_rank
from customer
GROUP BY category, `Item Purchased`)
SELECT 
    item_rank, Category, total_order, `Item Purchased`
FROM
    item_count
WHERE
    item_rank <= 3;

-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT 
    `Subscription Status`,
    COUNT(`Customer ID`) AS repeated_buyers
FROM
    customer
WHERE
    `Previous Purchases` > 5
GROUP BY `Subscription Status`;

-- Q10. What is the revenue contribution of each age group?
SELECT 
    SUM(`Purchase Amount (USD)`) AS total_revenue, Age
FROM
    customer
GROUP BY Age
ORDER BY total_revenue;